splitter: token_text_splitter  #semantic_splitter, sentence_text_splitter_LC
embedding: dkubex   #opnenai,huggingface, dkubex
metadata:
  - default
  #- custom
reader: #"https://llamahub.ai/l/file?from=loaders"
   - file
  # - scrapy_reader
  # - pyloader_reader
  # - github_reader

sentence_text_splitter_LC:
  chunk_size: 256
  chunk_overlap: 0

token_text_splitter:
  chunk_size: 256
  chunk_overlap: 0

mlflow:
  experiment: ingestion

# semantic_splitter:
#   buffer_size: 1
#   breakpoint_percentile_threshold: 95

huggingface:
  model: "BAAI/bge-large-en-v1.5"

#openai:
  #model: "text-embedding-ada-002"
  #llmkey: ""

dkubex:
  key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoib2NkbGdpdCIsInR5cGUiOiJhcGkiLCJpZCI6Ii9kZXBsb3ltZW50L2JnZS8ifQ.x0Zt-GkAsoyvvfBLQ5-aT7I2Ia_IokMunNc6KGa0Hyo"
  url: "https://a39d44034b53541deb754ffe25ee0d01-6a9d515a94d26bb2.elb.us-east-1.amazonaws.com/deployment/1/bge/"
  batch_size: 10

file:
  inputs:
    loader_args:
      input_dir: "/home/data/climate"
      recursive: true 
      exclude_hidden: true 
      raise_on_error: true 

#custom:
  #adjacent_chunks: False
  #extractor_path: <path>

# github_reader:
#   inputs:
#     loader_args:
#       input_dir: 
#       recursive: true 
#       exclude_hidden: true 
#       raise_on_error: true 
#     data_args:
#       doc_source: <name>
      
#scrapy_reader:
#  inputs:
#    loader_args:
#      test1: ""
#    data_args:
#      spiders:
#        spider1:
#          - path: /home/configs/spiders/quotess.py
#            url: 
#             - "https://quotes.toscrape.com/page/1/"
#             - "https://quotes.toscrape.com/page/2/"
# pyloader_reader:
#   inputs:
#     data_args:
#       - pyloader_path: /home/testscript.py      
